export const FETCH_INACTIVE_MERCHANTS = "FETCH_INACTIVE_MERCHANTS";
export const RESET_INACTIVE_MERCHANTS = "RESET_INACTIVE_MERCHANTS";
export const FETCH_CHARGE_BACKS = "FETCH_CHARGE_BACKS";
export const RESET_CHARGE_BACKS = "RESET_CHARGE_BACKS";
export const FETCH_EXPIRING_DOCUMENTS = "FETCH_EXPIRING_DOCUMENTS";
export const RESET_EXPIRING_DOCUMENTS = "RESET_EXPIRING_DOCUMENTS";
export const FETCH_TOP_TEN_MERCHANTS = "FETCH_TOP_TEN_MERCHANTS";
export const RESET_TOP_TEN_MERCHANTS = "RESET_TOP_TEN_MERCHANTS";
