export const GET_BUSINESS_LIST = "GET_BUSINESS_LIST";
export const GET_MERCHANT_DEVICE = "GET_MERCHANT_DEVICE";
export const GET_KYC_APPROVAL = "GET_KYC_APPROVAL";
export const GET_INVOICE_DETAILS = "GET_INVOICE_DETAILS";
export const RESET_LIST = "RESET_LIST";
export const GET_BUSINESS_PROFILE = "GET_BUSINESS_PROFILE";
export const GET_DUE_DILIGENCE = "GET_DUE_DILIGENCE";
export const UPDATE_BUSINESS_PROFILE = "UPDATE_BUSINESS_PROFILE";
