export const FETCH_CARDS = "FETCH_CARDS";
export const GET_CARDS = "GET_CARDS";
export const GET_CARD_DETAILS = "GET_CARD_DETAILS";
export const FETCH_CARDS_HISTORY = "FETCH_CARDS_HISTORY";
export const FETCH_CARDS_RECORD = "FETCH_CARDS_RECORD";
export const RESET_CARDS = "RESET_CARDS";
export const FETCH_STATUS = "FETCH_STATUS";
export const FETCH_MESSAGE = "FETCH_MESSAGE";
