export const GET_APPLICATIONS = "GET_APPLICATIONS";
export const RESET_APPLICATIONS = "RESET_APPLICATIONS";
export const FETCH_APPLICATION = "FETCH_APPLICATION";
export const GET_APPLICATION_STATUS = "GET_APPLICATION_STATUS";
export const UPLOAD_KYC_DOCS = "UPLOAD_KYC_DOCS";
export const UPDATE_KYC_DETAILS = "UPDATE_KYC_DETAILS";
export const UPDATE_KYC_STATUS = "UPDATE_KYC_STATUS";
